javaVersion=21
#Plugins
systemProp.kotlinVersion=2.1.10
#Dependencies
systemProp.kvisionVersion=8.2.0
systemProp.kspVersion=2.1.20-2.0.0
systemProp.kiluaRpcVersion=0.0.32

ktorVersion=3.0.3
hikariVersion=3.2.0
commonsCodecVersion=1.10
jdbcNamedParametersVersion=1.1
exposedVersion=0.17.14
logbackVersion=1.5.16
h2Version=1.4.197
pgsqlVersion=42.7.5
kweryVersion=0.17
bcryptVersion=0.4
koinVersion=4.0.4
coroutinesVersion=1.10.1
flaxoosVersion=2.1.2
kvisionTailwindCssVersion=9.0.0
ballastVersion=4.2.1

#Kotlin
kotlin.mpp.stability.nowarn=true
org.gradle.jvmargs=-Xmx2g
ksp.incremental=false
